export const navGroups = [
  {
    groupLabel: 'Manpower Agency',
    portal: 'agency',
    items: [
      {
        icon: 'LayoutDashboard',
        label: 'Agency Dashboard',
        portal: 'agency',
        submodule: 'dashboard',
        href: '/dashboard/agency/dashboard',
      },
      {
        icon: 'Building2',
        label: 'Clients & Accounts',
        portal: 'agency',
        childItems: [
          {
            label: 'All Clients',
            portal: 'agency',
            submodule: 'clients-all',
            href: '/dashboard/agency/clients-all',
          },
          {
            label: 'Add Client',
            portal: 'agency',
            submodule: 'clients-add',
            href: '/dashboard/agency/clients-add',
          },
          {
            label: 'Client Invoices & Bills',
            portal: 'agency',
            submodule: 'bills',
            href: '/dashboard/agency/bills',
          },
          {
            label: 'Client Payments',
            portal: 'agency',
            submodule: 'payments',
            href: '/dashboard/agency/payments',
          },
        ],
      },
      {
        icon: 'BarChart3',
        label: 'Placement Reports',
        portal: 'agency',
        submodule: 'reports',
        href: '/dashboard/agency/reports',
      },
    ],
  },
  /*
  {
    groupLabel: 'Brick Factory',
    portal: 'factory',
    items: [
      {
        icon: 'Factory',
        label: 'Factory Dashboard',
        portal: 'factory',
        submodule: 'dashboard',
        href: '/dashboard/factory/dashboard',
      },
      {
        icon: 'Users2',
        label: 'Worker Roster',
        portal: 'factory',
        submodule: 'employees',
        href: '/dashboard/factory/employees',
      },
      {
        icon: 'Receipt',
        label: 'Coal & Material Bills',
        portal: 'factory',
        submodule: 'bills',
        href: '/dashboard/factory/bills',
      },
      {
        icon: 'CreditCard',
        label: 'Wages & Payments',
        portal: 'factory',
        submodule: 'payments',
        href: '/dashboard/factory/payments',
      },
      {
        icon: 'BarChart3',
        label: 'Kiln & Production Telemetry',
        portal: 'factory',
        submodule: 'reports',
        href: '/dashboard/factory/reports',
      },
    ],
  },
  */
  {
    groupLabel: 'Document Studio',
    portal: 'docs',
    items: [
      {
        icon: 'FileText',
        label: 'Employment Agreement',
        portal: 'docs',
        submodule: 'agreement',
        href: '/dashboard/docs/agreement',
      },
      {
        icon: 'UserCheck',
        label: 'Customer & Guardian Form',
        portal: 'docs',
        submodule: 'customer-form',
        href: '/dashboard/docs/customer-form',
      },
      {
        icon: 'Stamp',
        label: 'Indian Visa Submission',
        portal: 'docs',
        submodule: 'indian-visa',
        href: '/dashboard/docs/indian-visa',
      },
      {
        icon: 'CreditCard',
        label: 'Passport Submission',
        portal: 'docs',
        submodule: 'passport-sub',
        href: '/dashboard/docs/passport-sub',
      },
      {
        icon: 'IdCard',
        label: 'Office ID Card',
        portal: 'docs',
        submodule: 'idcard',
        href: '/dashboard/docs/idcard',
      },
      {
        icon: 'Receipt',
        label: 'Monthly Salary Slip',
        portal: 'docs',
        submodule: 'payroll',
        href: '/dashboard/docs/payroll',
      },
      {
        icon: 'FileSpreadsheet',
        label: 'Invoice Billing',
        portal: 'docs',
        submodule: 'invoice',
        href: '/dashboard/docs/invoice',
      },
      {
        icon: 'Award',
        label: 'Experience Certificate',
        portal: 'docs',
        submodule: 'certificate-exp',
        href: '/dashboard/docs/certificate-exp',
      },
      {
        icon: 'ShieldCheck',
        label: 'Character Certificate',
        portal: 'docs',
        submodule: 'certificate-char',
        href: '/dashboard/docs/certificate-char',
      },
      {
        icon: 'Heart',
        label: 'Marriage Certificate',
        portal: 'docs',
        submodule: 'certificate-marr',
        href: '/dashboard/docs/certificate-marr',
      },
    ],
  },
  {
    groupLabel: 'Data Records Center',
    portal: 'data',
    items: [
      {
        icon: 'User',
        label: 'Customers (কাস্টমার)',
        portal: 'data',
        submodule: 'customer-profiles',
        href: '/dashboard/data/customer-profiles',
      },
      {
        icon: 'FileText',
        label: 'Agreement Records',
        portal: 'data',
        submodule: 'agreements',
        href: '/dashboard/data/agreements',
      },
      {
        icon: 'UserCheck',
        label: 'Customer Applications',
        portal: 'data',
        submodule: 'customer-applications',
        href: '/dashboard/data/customer-applications',
      },
      {
        icon: 'Stamp',
        label: 'Indian Visa Records',
        portal: 'data',
        submodule: 'indian-visas',
        href: '/dashboard/data/indian-visas',
      },
      {
        icon: 'CreditCard',
        label: 'Passport Submissions',
        portal: 'data',
        submodule: 'passports',
        href: '/dashboard/data/passports',
      },
      {
        icon: 'Receipt',
        label: 'Salary Slips',
        portal: 'data',
        submodule: 'salary-slips',
        href: '/dashboard/data/salary-slips',
      },
      {
        icon: 'FileSpreadsheet',
        label: 'Invoices & Billing',
        portal: 'data',
        submodule: 'invoices',
        href: '/dashboard/data/invoices',
      },
    ],
  },
  {
    groupLabel: 'System Administration',
    portal: 'admin',
    items: [
      {
        icon: 'Shield',
        label: 'System Users',
        portal: 'admin',
        submodule: 'users',
        href: '/dashboard/admin/users',
      },
      {
        icon: 'History',
        label: 'Audit & Database Logs',
        portal: 'admin',
        submodule: 'system-logs',
        href: '/dashboard/admin/system-logs',
      },
      {
        icon: 'Settings',
        label: 'Global Settings',
        portal: 'admin',
        submodule: 'settings',
        href: '/dashboard/admin/settings',
      },
    ],
  },
];
