export const navGroups = [
  {
    groupLabel: 'Manpower Agency',
    groupKey: 'nav.agency',
    portal: 'agency',
    items: [
      {
        icon: 'LayoutDashboard',
        label: 'Agency Dashboard',
        key: 'nav.agencyDashboard',
        portal: 'agency',
        submodule: 'dashboard',
        href: '/dashboard/agency/dashboard',
      },
      {
        icon: 'Building2',
        label: 'Clients & Accounts',
        key: 'nav.clientsAndAccounts',
        portal: 'agency',
        childItems: [
          {
            label: 'All Clients',
            key: 'nav.allClients',
            portal: 'agency',
            submodule: 'clients-all',
            href: '/dashboard/agency/clients-all',
          },
          {
            label: 'Add Client',
            key: 'nav.addClient',
            portal: 'agency',
            submodule: 'clients-add',
            href: '/dashboard/agency/clients-add',
          },
          {
            label: 'Client Invoices & Bills',
            key: 'nav.clientBills',
            portal: 'agency',
            submodule: 'bills',
            href: '/dashboard/agency/bills',
          },
          {
            label: 'Client Payments',
            key: 'nav.clientPayments',
            portal: 'agency',
            submodule: 'payments',
            href: '/dashboard/agency/payments',
          },
        ],
      },
    ],
  },
  /*
  {
    groupLabel: 'Brick Factory',
    groupKey: 'nav.factory',
    portal: 'factory',
    items: [
      {
        icon: 'Factory',
        label: 'Factory Dashboard',
        key: 'nav.factoryDashboard',
        portal: 'factory',
        submodule: 'dashboard',
        href: '/dashboard/factory/dashboard',
      },
      {
        icon: 'Users2',
        label: 'Worker Roster',
        key: 'nav.workerRoster',
        portal: 'factory',
        submodule: 'employees',
        href: '/dashboard/factory/employees',
      },
      {
        icon: 'Receipt',
        label: 'Coal & Material Bills',
        key: 'nav.coalBills',
        portal: 'factory',
        submodule: 'bills',
        href: '/dashboard/factory/bills',
      },
      {
        icon: 'CreditCard',
        label: 'Wages & Payments',
        key: 'nav.wagesPayments',
        portal: 'factory',
        submodule: 'payments',
        href: '/dashboard/factory/payments',
      },
      {
        icon: 'BarChart3',
        label: 'Kiln & Production Telemetry',
        key: 'nav.kilnReports',
        portal: 'factory',
        submodule: 'reports',
        href: '/dashboard/factory/reports',
      },
    ],
  },
  */
  {
    groupLabel: 'Document Studio',
    groupKey: 'nav.docs',
    portal: 'docs',
    items: [
      {
        icon: 'FileText',
        label: 'Employment Agreement',
        key: 'nav.employmentAgreement',
        portal: 'docs',
        submodule: 'agreement',
        href: '/dashboard/docs/agreement',
      },
      {
        icon: 'UserCheck',
        label: 'Customer & Guardian Form',
        key: 'nav.customerGuardianForm',
        portal: 'docs',
        submodule: 'customer-form',
        href: '/dashboard/docs/customer-form',
      },
      {
        icon: 'Stamp',
        label: 'Indian Visa Submission',
        key: 'nav.indianVisaRecords',
        portal: 'docs',
        submodule: 'indian-visa',
        href: '/dashboard/docs/indian-visa',
      },
      {
        icon: 'CreditCard',
        label: 'Passport Submission',
        key: 'nav.passportRecords',
        portal: 'docs',
        submodule: 'passport-sub',
        href: '/dashboard/docs/passport-sub',
      },
      {
        icon: 'IdCard',
        label: 'Employee ID Card',
        key: 'nav.idCard',
        portal: 'docs',
        submodule: 'idcard',
        href: '/dashboard/docs/idcard',
      },
      {
        icon: 'Receipt',
        label: 'Monthly Salary Slip',
        key: 'nav.salarySlip',
        portal: 'docs',
        submodule: 'payroll',
        href: '/dashboard/docs/payroll',
      },
      {
        icon: 'FileSpreadsheet',
        label: 'Invoice Billing',
        key: 'nav.invoice',
        portal: 'docs',
        submodule: 'invoice',
        href: '/dashboard/docs/invoice',
      },
      {
        icon: 'Award',
        label: 'Experience Certificate',
        key: 'nav.experienceCertificate',
        portal: 'docs',
        submodule: 'certificate-exp',
        href: '/dashboard/docs/certificate-exp',
      },
      {
        icon: 'ShieldCheck',
        label: 'Character Certificate',
        key: 'nav.characterCertificate',
        portal: 'docs',
        submodule: 'certificate-char',
        href: '/dashboard/docs/certificate-char',
      },
      {
        icon: 'Heart',
        label: 'Marriage Certificate',
        key: 'nav.marriageCertificate',
        portal: 'docs',
        submodule: 'certificate-marr',
        href: '/dashboard/docs/certificate-marr',
      },
    ],
  },
  {
    groupLabel: 'Data Records Center',
    groupKey: 'nav.data',
    portal: 'data',
    items: [
      {
        icon: 'User',
        label: 'Customer Profiles',
        key: 'nav.customerProfiles',
        portal: 'data',
        submodule: 'customer-profiles',
        href: '/dashboard/data/customer-profiles',
      },
      {
        icon: 'FileText',
        label: 'Agreement Records',
        key: 'nav.agreementRecords',
        portal: 'data',
        submodule: 'agreements',
        href: '/dashboard/data/agreements',
      },
      {
        icon: 'UserCheck',
        label: 'Customer Applications',
        key: 'nav.customerApplications',
        portal: 'data',
        submodule: 'customer-applications',
        href: '/dashboard/data/customer-applications',
      },
      {
        icon: 'Stamp',
        label: 'Indian Visa Records',
        key: 'nav.indianVisaRecords',
        portal: 'data',
        submodule: 'indian-visas',
        href: '/dashboard/data/indian-visas',
      },
      {
        icon: 'CreditCard',
        label: 'Passport Submissions',
        key: 'nav.passportRecords',
        portal: 'data',
        submodule: 'passports',
        href: '/dashboard/data/passports',
      },
      {
        icon: 'Receipt',
        label: 'Salary Slips',
        key: 'nav.salarySlipRecords',
        portal: 'data',
        submodule: 'salary-slips',
        href: '/dashboard/data/salary-slips',
      },
      {
        icon: 'FileSpreadsheet',
        label: 'Invoices & Billing',
        key: 'nav.invoiceRecords',
        portal: 'data',
        submodule: 'invoices',
        href: '/dashboard/data/invoices',
      },
    ],
  },
  {
    groupLabel: 'System Administration',
    groupKey: 'nav.admin',
    portal: 'admin',
    items: [
      {
        icon: 'Shield',
        label: 'System Users',
        key: 'nav.systemUsers',
        portal: 'admin',
        submodule: 'users',
        href: '/dashboard/admin/users',
      },
      {
        icon: 'History',
        label: 'Audit & Database Logs',
        key: 'nav.auditLogs',
        portal: 'admin',
        submodule: 'system-logs',
        href: '/dashboard/admin/system-logs',
      },
      {
        icon: 'Settings',
        label: 'Global Settings',
        key: 'nav.globalSettings',
        portal: 'admin',
        submodule: 'settings',
        href: '/dashboard/admin/settings',
      },
    ],
  },
];
