import mongoose, { Schema, model } from "mongoose";
import { generateDid } from "../utils/generateDid.js";

const { models } = mongoose;

/**
 * Generates unique receipt / token number: MR-YYMMDD-XXXX (e.g. MR-260819-4921)
 */
export function generateReceiptTokenNo() {
  const date = new Date();
  const yy = String(date.getFullYear()).slice(-2);
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  const randomSuffix = Math.floor(1000 + Math.random() * 9000);
  return `MR-${yy}${mm}${dd}-${randomSuffix}`;
}

const moneyReceiptSchema = new Schema(
  {
    did: {
      type: String,
      default: () => generateDid(),
      unique: true,
      index: true,
    },
    receiptNo: {
      type: String,
      unique: true,
      index: true,
      default: generateReceiptTokenNo,
    },
    // Central Customer reference if available
    customerId: {
      type: Schema.Types.ObjectId,
      ref: "Customer",
      default: null,
      index: true,
    },
    // Source document linking (e.g. Indian Visa, Passport, CaseFile, Invoice)
    serviceRef: {
      modelName: { type: String, default: "" }, // 'IndianVisaSubmission', 'PassportSubmission', 'CaseFile', 'Invoice', etc.
      docId: { type: Schema.Types.ObjectId, default: null },
      trackingId: { type: String, default: "" },
    },

    // Client details
    clientName: {
      type: String,
      required: [true, "Client name is required"],
      trim: true,
      index: true,
    },
    clientPhone: {
      type: String,
      trim: true,
      default: "",
      index: true,
    },
    passportNumber: {
      type: String,
      trim: true,
      uppercase: true,
      default: "",
      index: true,
    },

    // Service & Payment details
    serviceType: {
      type: String,
      required: [true, "Service type is required"],
      trim: true,
      default: "অন্যান্য (General Service)",
    },
    purpose: {
      type: String,
      trim: true,
      default: "",
    },
    amount: {
      type: Number,
      required: [true, "Amount is required"],
      min: [0, "Amount cannot be negative"],
    },
    amountInWords: {
      type: String,
      trim: true,
      default: "",
    },
    currency: {
      type: String,
      default: "BDT",
    },
    paymentMethod: {
      type: String,
      enum: ["Cash", "Bank Transfer", "bKash/Nagad", "Cheque", "Other"],
      default: "Cash",
    },

    // Internal Lifecycle Status
    // pending: Token generated by manager, awaiting payment at cashier/accountant
    // confirmed: Cash received & sealed by accountant
    // cancelled: Voided / Cancelled
    status: {
      type: String,
      enum: ["pending", "confirmed", "cancelled"],
      default: "pending",
      index: true,
    },

    // Manager / Token Creator
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    createdByName: {
      type: String,
      default: "ম্যানেজার (Manager)",
    },

    // Cashier / Accountant (Seal/Confirmation)
    confirmedBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    confirmedByName: {
      type: String,
      default: "",
    },
    confirmedAt: {
      type: Date,
      default: null,
    },

    // Bank Deposit & Turnover Management
    handedOverToBank: {
      type: Boolean,
      default: false,
    },
    bankDepositRef: {
      type: String,
      default: "",
    },
    bankDepositDate: {
      type: Date,
      default: null,
    },

    notes: {
      type: String,
      default: "",
    },
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

// Ensure receipt number generation before save
moneyReceiptSchema.pre("save", function (next) {
  if (!this.receiptNo) {
    this.receiptNo = generateReceiptTokenNo();
  }
  next();
});

moneyReceiptSchema.index({
  receiptNo: "text",
  clientName: "text",
  clientPhone: "text",
  passportNumber: "text",
  serviceType: "text",
});

export const MoneyReceiptModel = models.MoneyReceipt || model("MoneyReceipt", moneyReceiptSchema);
export default MoneyReceiptModel;
