export const navGroups = [
  {
    groupLabel: 'Agency',
    groupKey: 'nav.agency',
    portal: 'agency',
    items: [
      {
        icon: 'LayoutDashboard',
        label: 'Overview',
        key: 'nav.agencyDashboard',
        portal: 'agency',
        submodule: 'dashboard',
        href: '/dashboard/agency/dashboard',
      },
      {
        icon: 'Building2',
        label: 'Clients & Accounts',
        key: 'nav.clientsAndAccounts',
        portal: 'agency',
        childItems: [
          {
            icon: 'Users',
            label: 'All Clients',
            key: 'nav.allClients',
            portal: 'agency',
            submodule: 'clients-all',
            href: '/dashboard/agency/clients-all',
          },
          {
            icon: 'UserPlus',
            label: 'Add Client',
            key: 'nav.addClient',
            portal: 'agency',
            submodule: 'clients-add',
            href: '/dashboard/agency/clients-add',
          },
          {
            icon: 'Receipt',
            label: 'Client Invoices & Bills',
            key: 'nav.clientBills',
            portal: 'agency',
            submodule: 'bills',
            href: '/dashboard/agency/bills',
          },
          {
            icon: 'CreditCard',
            label: 'Client Payments',
            key: 'nav.clientPayments',
            portal: 'agency',
            submodule: 'payments',
            href: '/dashboard/agency/payments',
          },
        ],
      },
    ],
  },
  {
    groupLabel: 'Document Studio',
    groupKey: 'nav.docs',
    portal: 'docs',
    items: [
      {
        icon: 'FileSignature',
        label: 'Employment Agreement',
        key: 'nav.employmentAgreement',
        portal: 'docs',
        submodule: 'agreement',
        href: '/dashboard/docs/agreement',
      },
      {
        icon: 'UserCheck',
        label: 'Customer & Guardian Form',
        key: 'nav.customerGuardianForm',
        portal: 'docs',
        submodule: 'customer-form',
        href: '/dashboard/docs/customer-form',
      },
      {
        icon: 'Stamp',
        label: 'Indian Visa Submission',
        key: 'nav.indianVisaRecords',
        portal: 'docs',
        submodule: 'indian-visa',
        href: '/dashboard/docs/indian-visa',
      },
      {
        icon: 'BookOpen',
        label: 'Passport Submission',
        key: 'nav.passportRecords',
        portal: 'docs',
        submodule: 'passport-sub',
        href: '/dashboard/docs/passport-sub',
      },
      {
        icon: 'Contact',
        label: 'Employee ID Card',
        key: 'nav.idCard',
        portal: 'docs',
        submodule: 'idcard',
        href: '/dashboard/docs/idcard',
      },
      {
        icon: 'Banknote',
        label: 'Monthly Salary Slip',
        key: 'nav.salarySlip',
        portal: 'docs',
        submodule: 'payroll',
        href: '/dashboard/docs/payroll',
      },
      {
        icon: 'ReceiptText',
        label: 'Invoice Billing',
        key: 'nav.invoice',
        portal: 'docs',
        submodule: 'invoice',
        href: '/dashboard/docs/invoice',
      },
      {
        icon: 'Receipt',
        label: 'Money Receipt Voucher',
        key: 'nav.moneyReceipt',
        portal: 'docs',
        submodule: 'money-receipt',
        href: '/dashboard/docs/money-receipt',
      },
      {
        icon: 'Wallet',
        label: 'Cash Money Voucher',
        key: 'nav.cashVoucher',
        portal: 'docs',
        submodule: 'cash-voucher',
        href: '/dashboard/docs/cash-voucher',
      },
      {
        icon: 'Award',
        label: 'Certificates',
        key: 'nav.certificatesStudio',
        childItems: [
          {
            icon: 'Award',
            label: 'Experience Certificate',
            key: 'nav.experienceCertificate',
            portal: 'docs',
            submodule: 'experience-certificate',
            href: '/dashboard/docs/experience-certificate',
          },
          {
            icon: 'ShieldCheck',
            label: 'Character Certificate',
            key: 'nav.characterCertificate',
            portal: 'docs',
            submodule: 'character-certificate',
            href: '/dashboard/docs/character-certificate',
          },
          {
            icon: 'Heart',
            label: 'Marriage Certificate',
            key: 'nav.marriageCertificate',
            portal: 'docs',
            submodule: 'marriage-certificate',
            href: '/dashboard/docs/marriage-certificate',
          },
        ],
      },
    ],
  },
  {
    groupLabel: 'Data Records Center',
    groupKey: 'nav.data',
    portal: 'data',
    items: [
      {
        icon: 'Users',
        label: 'Customer Profiles',
        key: 'nav.customerProfiles',
        portal: 'data',
        submodule: 'customer-profiles',
        href: '/dashboard/data/customer-profiles',
      },
      {
        icon: 'FileSignature',
        label: 'Agreement Records',
        key: 'nav.agreementRecords',
        portal: 'data',
        submodule: 'agreements',
        href: '/dashboard/data/agreements',
      },
      {
        icon: 'UserCheck',
        label: 'Customer Applications',
        key: 'nav.customerApplications',
        portal: 'data',
        submodule: 'customer-applications',
        href: '/dashboard/data/customer-applications',
      },
      {
        icon: 'Stamp',
        label: 'Indian Visa Records',
        key: 'nav.indianVisaRecords',
        portal: 'data',
        submodule: 'indian-visas',
        href: '/dashboard/data/indian-visas',
      },
      {
        icon: 'BookOpen',
        label: 'Passport Submissions',
        key: 'nav.passportRecords',
        portal: 'data',
        submodule: 'passports',
        href: '/dashboard/data/passports',
      },
      {
        icon: 'Banknote',
        label: 'Salary Slips',
        key: 'nav.salarySlipRecords',
        portal: 'data',
        submodule: 'salary-slips',
        href: '/dashboard/data/salary-slips',
      },
      {
        icon: 'ReceiptText',
        label: 'Invoices & Billing',
        key: 'nav.invoiceRecords',
        portal: 'data',
        submodule: 'invoices',
        href: '/dashboard/data/invoices',
      },
    ],
  },
  {
    groupLabel: 'System Administration',
    groupKey: 'nav.admin',
    portal: 'admin',
    items: [
      {
        icon: 'Users',
        label: 'System Users',
        key: 'nav.systemUsers',
        portal: 'admin',
        submodule: 'users',
        href: '/dashboard/admin/users',
      },
      {
        icon: 'History',
        label: 'Audit & Database Logs',
        key: 'nav.auditLogs',
        portal: 'admin',
        submodule: 'system-logs',
        href: '/dashboard/admin/system-logs',
      },
      {
        icon: 'Settings2',
        label: 'Global Settings',
        key: 'nav.globalSettings',
        portal: 'admin',
        submodule: 'settings',
        href: '/dashboard/admin/settings',
      },
    ],
  },
];
