export const navGroups = [
  {
    groupLabel: '',
    groupKey: '',
    portal: 'agency',
    items: [
      {
        icon: 'CheckSquare',
        label: 'My Tasks',
        key: 'nav.myTasks',
        portal: 'agency',
        submodule: 'tasks',
        href: '/dashboard/agency/tasks',
      },
      {
        icon: 'FolderOpen',
        label: 'Case Files',
        key: 'nav.caseFiles',
        portal: 'agency',
        submodule: 'cases',
        href: '/dashboard/agency/cases',
      },
      {
        icon: 'Building2',
        label: 'Clients & Accounts',
        key: 'nav.clientsAndAccounts',
        portal: 'agency',
        childItems: [
          {
            icon: 'Users',
            label: 'All Clients',
            key: 'nav.allClients',
            portal: 'agency',
            submodule: 'clients-all',
            href: '/dashboard/agency/clients-all',
          },
          {
            icon: 'UserPlus',
            label: 'Add Client',
            key: 'nav.addClient',
            portal: 'agency',
            submodule: 'clients-add',
            href: '/dashboard/agency/clients-add',
          },
        ],
      },
      {
        icon: 'FileText',
        label: 'Document Studio',
        key: 'nav.docs',
        portal: 'docs',
        childItems: [
          {
            icon: 'LayoutGrid',
            label: 'All Generators (Studio Hub)',
            key: 'nav.documentStudioHub',
            portal: 'docs',
            submodule: 'overview',
            href: '/dashboard/docs/overview',
          },
          {
            icon: 'FileSignature',
            label: 'Employment Agreement',
            key: 'nav.employmentAgreement',
            portal: 'docs',
            submodule: 'agreement',
            href: '/dashboard/docs/agreement',
          },
          {
            icon: 'UserCheck',
            label: 'Client & Guardian Form',
            key: 'nav.clientGuardianForm',
            portal: 'docs',
            submodule: 'client-form',
            href: '/dashboard/docs/client-form',
          },
          {
            icon: 'Stamp',
            label: 'Indian Visa Submission',
            key: 'nav.indianVisaRecords',
            portal: 'docs',
            submodule: 'indian-visa',
            href: '/dashboard/docs/indian-visa',
          },
          {
            icon: 'BookOpen',
            label: 'Passport Submission',
            key: 'nav.passportRecords',
            portal: 'docs',
            submodule: 'passport-sub',
            href: '/dashboard/docs/passport-sub',
          },
          {
            icon: 'Contact',
            label: 'Employee ID Card',
            key: 'nav.idCard',
            portal: 'docs',
            submodule: 'idcard',
            href: '/dashboard/docs/idcard',
          },
          {
            icon: 'Banknote',
            label: 'Monthly Salary Slip',
            key: 'nav.salarySlip',
            portal: 'docs',
            submodule: 'payroll',
            href: '/dashboard/docs/payroll',
          },
          {
            icon: 'ReceiptText',
            label: 'Invoice Billing',
            key: 'nav.invoice',
            portal: 'docs',
            submodule: 'invoice',
            href: '/dashboard/docs/invoice',
          },
          {
            icon: 'Receipt',
            label: 'Money Receipt Voucher',
            key: 'nav.moneyReceipt',
            portal: 'docs',
            submodule: 'money-receipt',
            href: '/dashboard/docs/money-receipt',
          },
          {
            icon: 'Wallet',
            label: 'Cash Money Voucher',
            key: 'nav.cashVoucher',
            portal: 'docs',
            submodule: 'cash-voucher',
            href: '/dashboard/docs/cash-voucher',
          },
          {
            icon: 'Award',
            label: 'Experience Certificate',
            key: 'nav.experienceCertificate',
            portal: 'docs',
            submodule: 'experience-certificate',
            href: '/dashboard/docs/experience-certificate',
          },
          {
            icon: 'ShieldCheck',
            label: 'Character Certificate',
            key: 'nav.characterCertificate',
            portal: 'docs',
            submodule: 'character-certificate',
            href: '/dashboard/docs/character-certificate',
          },
          {
            icon: 'Heart',
            label: 'Marriage Certificate',
            key: 'nav.marriageCertificate',
            portal: 'docs',
            submodule: 'marriage-certificate',
            href: '/dashboard/docs/marriage-certificate',
          },
        ],
      },
    ],
  },
  {
    groupLabel: 'Data Records Center',
    groupKey: 'nav.data',
    portal: 'data',
    items: [
      {
        icon: 'Users',
        label: 'Client Profiles',
        key: 'nav.clientProfiles',
        portal: 'data',
        submodule: 'client-profiles',
        href: '/dashboard/data/client-profiles',
      },
      {
        icon: 'FileSignature',
        label: 'Agreement Records',
        key: 'nav.agreementRecords',
        portal: 'data',
        submodule: 'agreements',
        href: '/dashboard/data/agreements',
      },
      {
        icon: 'UserCheck',
        label: 'Client Applications',
        key: 'nav.clientApplications',
        portal: 'data',
        submodule: 'client-applications',
        href: '/dashboard/data/client-applications',
      },
      {
        icon: 'Stamp',
        label: 'Indian Visa Records',
        key: 'nav.indianVisaRecords',
        portal: 'data',
        submodule: 'indian-visas',
        href: '/dashboard/data/indian-visas',
      },
      {
        icon: 'BookOpen',
        label: 'Passport Submissions',
        key: 'nav.passportRecords',
        portal: 'data',
        submodule: 'passports',
        href: '/dashboard/data/passports',
      },
      {
        icon: 'Banknote',
        label: 'Salary Slips',
        key: 'nav.salarySlipRecords',
        portal: 'data',
        submodule: 'salary-slips',
        href: '/dashboard/data/salary-slips',
      },
      {
        icon: 'ReceiptText',
        label: 'Invoices & Billing',
        key: 'nav.invoiceRecords',
        portal: 'data',
        submodule: 'invoices',
        href: '/dashboard/data/invoices',
      },
    ],
  },
];

